@startuml
annotation java.lang.Override
annotation javafx.fxml.FXML
class application.AESEncryption
class application.ColoredCell
class application.DatabaseHandler
class application.ListInterface
class application.Request
class application.User
class application.Yaccount
class controller.AdminController
class controller.BasicController
class controller.LoginController
class controller.RegisterController
class java.io.UnsupportedEncodingException
class java.lang.reflect.Field
class java.net.URL
class java.nio.charset.StandardCharsets
class java.security.InvalidKeyException
class java.security.MessageDigest
class java.security.NoSuchAlgorithmException
class java.sql.Date
class java.sql.ResultSet
class java.sql.SQLException
class java.time.LocalDate
class java.util.Arrays
class java.util.Base64
class java.util.HashMap
class java.util.LinkedList
class java.util.Map
class java.util.Queue
class java.util.ResourceBundle
class java.util.Stack
class javafx.application.Application
class javafx.beans.value.ChangeListener
class javafx.beans.value.ObservableValue
class javafx.event.ActionEvent
class javafx.fxml.FXMLLoader
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.ListCell
class javafx.scene.control.ListView
class javafx.stage.Stage
class javafx.util.Callback
class javax.crypto.BadPaddingException
class javax.crypto.Cipher
class javax.crypto.IllegalBlockSizeException
class javax.crypto.NoSuchPaddingException
class javax.crypto.spec.SecretKeySpec
interface javafx.fxml.Initializable
application.ColoredCell ..> java.lang.Override
application.ColoredCell --|> javafx.scene.control.ListCell
application.ListInterface ..> java.lang.Override
application.ListInterface ..> application.Yaccount
application.Yaccount ..> java.lang.Override
application.Yaccount --|> javafx.application.Application
controller.AdminController ..> java.lang.Override
controller.AdminController ..> javafx.fxml.FXML
controller.AdminController ..> application.Yaccount
controller.AdminController --|> javafx.fxml.Initializable
controller.BasicController ..> java.lang.Override
controller.BasicController ..> javafx.fxml.FXML
controller.BasicController ..> application.Yaccount
controller.BasicController --|> javafx.fxml.Initializable
controller.LoginController ..> java.lang.Override
controller.LoginController ..> javafx.fxml.FXML
controller.LoginController ..> application.Yaccount
controller.LoginController --|> javafx.fxml.Initializable
controller.RegisterController ..> java.lang.Override
controller.RegisterController ..> javafx.fxml.FXML
controller.RegisterController ..> application.Yaccount
controller.RegisterController --|> javafx.fxml.Initializable
@enduml